___
# Atividade: <p> <center> Variáveis aleatórias discretas
___

## Aula 08

**Objetivo da aula:** Ao final desta aula, o aluno deve ser capaz de:
 * Descrever e aplicar propriedades de distribuições de probabilidades de variáveis aleatórias discretas; e
 * Compreender e aplicar propriedades de esperança e variância.


___
<div id="indice"></div>

## Índice

- [Corretora de Seguros](#corretora-de-seguros)
    - [Exercício 1](#ex1)
    - [Exercício 2](#ex2)
    - [Exercício 3](#ex3)
    - [Exercício 4](#ex4)
    - [Exercício 5](#ex5)
    - [Exercício 6](#ex6)


In [6]:
import numpy as np
import random
import pandas as pd
from math import *

___
<div id="corretora-de-seguros"></div>

## Corretora de Seguros

Uma corretora de seguros paga uma comissão de R\\$ 50,00 a cada novo seguro que um corretor vende. <br>
A probabilidade de um cliente adquirir o seguro é de 0,20. <br> 
a) Descreva como pode se comportar a comissão se um corretor ao abordar 2 clientes de maneira independente um do outro.<br>
b) Qual a probabilidade de um corretor ganhar apenas R\\$ 50,00?

**Resolução:** <p>
Primeiramente, vamos definir os seguintes eventos de acordo com enunciado:

- $S_i$: o cliente $i$ compra o seguro;
- $N_i ou S_i^C$: o cliente $i$ não compra o seguro.

Ainda, pelo enunciado sabemos que:

- $P(S_i) = 0.2$
- $P(N_i) = P(S_i^C) = 1 - P(S_i) = 0.8$

**item (a)**<br>
Lendo o enunciado, é fácil perceber que os possíveis valores que o corretor pode receber ao final de duas visitas são: 
**0 reais**, **50 reais** ou **100 reais**. <br>
Porém, qual a probabilidade que representa cada um desses valores acontecerem? Seria 1/3? <p>
A seguir, mostramos como construir a **distribuição de probabilidades desses possíveis valores que representam a comissão do corretor** ao final das duas visitas.

Listando todas as possíveis combinações de eventos de compra ou não compra do seguro de cada cliente, temos:

Cliente 1 | Cliente 2 | &nbsp; Probabilidade &nbsp; &nbsp;&nbsp; &nbsp; | Valor da comissão
:-------: | :-------: | :--------------------------:| :---:
$N_1$     | $N_2$     | $P(N_1)P(N_2|N_1)$ = $0.64$ | 0
$N_1$     | $S_2$     | $P(N_1)P(S_2|N_1)$ = $0.16$ | 50
$S_1$     | $N_2$     | $P(S_1)P(N_2|S_1)$ = $0.16$ | 50
$S_1$     | $S_2$     | $P(S_1)P(S_2|S_1)$ = $0.04$ | 100

<br>

Agora, como estamos interessados em descrever os possíveis valores da comissão de um corretor e suas respectivas probabilidade, vamos definir uma letra que represente essa variável aleatória:

- $X$: valor da comissão do corretor ao final do dia, representando um valor aleatório;

em que $x$ = 0; 50; e 100 representando os possíveis valores que essa variável aleatória $X$ pode assumir.


**item (b)**<br>
Assim, o qual é o valor de $P(X=50)$?

Consultando a tabela construída acima, vemos que $P(X=50) = 0.16 + 0.16 = 0.32$.

<div id="ex1"></div>

### EXERCÍCIO 1

Calcule o valor esperado e a variância da variável $X$.

*Resposta esperada para esperança e variância respectivamente: 20.0 reais ; 800.0 reais^2*

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [5]:
# Defina uma lista de valores
valores = [0, 50, 50, 100]

# Defina uma lista de pesos correspondentes
pesos = [0.64, 0.16, 0.16, 0.04]

# Calcule a média ponderada
soma_produto = sum(valor * peso for valor, peso in zip(valores, pesos))
soma_pesos = sum(pesos)
media_ponderada = soma_produto / soma_pesos
print('X:', media_ponderada)

X: 20.0


In [47]:
# Média
media_normal = sum(valores) / len(valores)

# Variância
variancia = sum(pow(valor - media_ponderada, 2) * peso for valor, peso in zip(valores, pesos))
print('Variância:', variancia)
print('Desvio Padrão:', pow(variancia, 0.5))

Variância: 800.0
Desvio Padrão: 28.284271247461902


___
## Tomando uma decisão

Imagine que a corretora de seguros irá fornecer um aumento na comissão dos corretores. Entretanto, cada corretor poderá escolher uma das seguintes opções:

- **Opção 1:** Defina $Y$ como a nova comissão que será a comissão atual mais um fixo de R\\$ 30,00;
- **Opção 2:** Defina $W$ como a nova comissão será o triplo da atual comissão.

<br>

A ideia aqui é fazer uma escolha de qual delas é melhor para aumentar o ganho de um corretor. 

Para isso, resolva os exercícios a seguir para auxiliá-lo nessa escolha.

<div id="ex2"></div>

### EXERCÍCIO 2

Construa a distribuição de probabilidade de $Y$ e de $W$ de acordo com cada uma das opções descritas acima.


In [34]:
df_Y = pd.DataFrame(columns=['Probabilidade', 'Valor da comissão'])
df_Y['Probabilidade'] = pd.Series(pesos)
df_Y['Valor da comissão'] = pd.Series(valores) + 30

df_W = pd.DataFrame(columns=['Probabilidade', 'Valor da comissão'])
df_W['Probabilidade'] = pd.Series(pesos)
df_W['Valor da comissão'] = pd.Series(valores) * 3

In [38]:
df_Y

Probabilidade  Valor da comissão
0           0.64                 30
1           0.16                 80
2           0.16                 80
3           0.04                130

In [39]:
df_W

Probabilidade  Valor da comissão
0           0.64                  0
1           0.16                150
2           0.16                150
3           0.04                300

<div id="ex3"></div>

### EXERCÍCIO 3

Considerando as respectivas distribuições de probabilidades, calcule o valor esperado e a variância para cada opção. 

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [45]:
pesos_Y = list(df_Y['Probabilidade'])
valores_Y = list(df_Y['Valor da comissão'])
media_ponderada_Y = sum(peso * valor for peso, valor in zip(pesos_Y, valores_Y))
variancia_Y = sum(pow(valor - media_ponderada_Y, 2) * peso for valor, peso in zip(valores_Y, pesos_Y))

print('Valor esperado em Y:', media_ponderada_Y)
print('Variância em Y:', variancia_Y)
print('Desvio padrão em Y:', pow(variancia_Y, 0.5))

Valor esperado em Y: 50.0
Variância em Y: 800.0
Desvio padrão em Y: 28.284271247461902


In [48]:
pesos_W = list(df_W['Probabilidade'])
valores_W = list(df_W['Valor da comissão'])
media_ponderada_W = sum(peso * valor for peso, valor in zip(pesos_W, valores_W))
variancia_W = sum(pow(valor - media_ponderada_W, 2) * peso for valor, peso in zip(valores_W, pesos_W))

print('Valor esperado em W:', media_ponderada_W)
print('Variância em W:', variancia_W)
print('Desvio padrão em W:', pow(variancia_W, 0.5))

Valor esperado em W: 60.0
Variância em W: 7200.0
Desvio padrão em W: 84.8528137423857


<div id="ex4"></div>

### EXERCÍCIO 4

Baseado nas propriedades da esperança (nos slides), calcule o valor esperado para a nova comissão em cada uma das opções.

*Resposta esperada para esperança opção 1 e 2 respectivamente: 50.0 reais ; 60.0 reais*

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [49]:
print('Valor esperado em Y:', media_ponderada_Y)
print('Valor esperado em W:', media_ponderada_W)

Valor esperado em Y: 50.0
Valor esperado em W: 60.0


<div id="ex5"></div>

### EXERCÍCIO 5

Baseado nas propriedades da variância (nos slides), calcule a variância para a nova comissão em cada uma das opções.

*Resposta esperada para variância opção 1 e 2 respectivamente: 800.0 reais^2 ; 7200.0 reais^2*

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [50]:
print('Variância em Y:', variancia_Y)
print('Variância em W:', variancia_W)

Variância em Y: 800.0
Variância em W: 7200.0


<div id="ex6"></div>

### EXERCÍCIO 6

Baseado nos resultados acima, qual opção você recomendaria para um corretor?

# Referências

1. MONTGOMERY, D. et al. Estatística Aplicada e Probabilidade para Engenheiros. 6. ed. Seções 2.8 e 3.1
1. MAGALHÃES, M. et al. Noções de Probabilidade e Estatística. 7. ed. Seções 3.1 e definições 4.2 (p. 110) e 4.5 (p. 121)